- name: Patch system and notify
  hosts: all
  become: yes
  vars:
    update_script_path: /tmp/update.sh
    notify_script_path: /tmp/notify.sh
    wallpaper_src: images/aravind.jpeg
    wallpaper_dest: /usr/share/backgrounds/aravind.jpeg
    desktop_user: "{{ ansible_user | default('intern') }}"

  tasks:

    - name: 📤 Copy update script to remote host
      copy:
        src: update.sh
        dest: "{{ update_script_path }}"
        mode: '0755'
        force: yes

    - name: ▶️ Run update script asynchronously
      shell: bash "{{ update_script_path }}"
      async: 600
      poll: 10
      register: update_result
      ignore_errors: yes

    - name: ✅ Print update result status
      debug:
        msg: "✅ Update script finished with RC={{ update_result.rc }}"

    - name: ❌ Fail if update script failed
      fail:
        msg: >-
          ❌ Update script failed.
          RC: {{ update_result.rc }}
          STDERR: {{ update_result.stderr | default('N/A') }}
      when: update_result.rc != 0

    - name: 📤 Copy notify script to remote host
      copy:
        src: notify.sh
        dest: "{{ notify_script_path }}"
        mode: '0755'
        force: yes

    - name: ▶️ Run notify script
      shell: bash "{{ notify_script_path }}"
      register: notify_result
      ignore_errors: yes

    - name: 📬 Show notify script result
      debug:
        msg: "✅ Notify script finished with RC={{ notify_result.rc }}"

    - name: ❌ Fail if notify script failed
      fail:
        msg: >-
          ❌ Notify script failed.
          RC: {{ notify_result.rc }}
          STDERR: {{ notify_result.stderr | default('N/A') }}
      when: notify_result.rc != 0

    - name: 🖼️ Copy wallpaper to remote machine
      copy:
        src: "{{ wallpaper_src }}"
        dest: "{{ wallpaper_dest }}"
        mode: '0644'

    - name: 🧠 Set GNOME wallpaper using gsettings
      become_user: "{{ desktop_user }}"
      shell: |
        export DISPLAY=:0
        export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u {{ desktop_user }})/bus
        gsettings set org.gnome.desktop.background picture-uri "file://{{ wallpaper_dest }}"
      when: ansible_facts['env']['XDG_CURRENT_DESKTOP'] is defined and "'GNOME' in ansible_facts['env']['XDG_CURRENT_DESKTOP']"

    - name: 🎨 Set XFCE wallpaper using xfconf-query
      become_user: "{{ desktop_user }}"
      shell: |
        export DISPLAY=:0
        xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/image-path --set "{{ wallpaper_dest }}"
      when: ansible_facts['env']['XDG_CURRENT_DESKTOP'] is defined and "'XFCE' in ansible_facts['env']['XDG_CURRENT_DESKTOP']"
