- name: Patch system and notify
  hosts: all
  become: yes
  become_method: sudo
  tasks:

    - name: Copy update.sh to target machine
      copy:
        src: update.sh
        dest: /tmp/update.sh
        mode: '0755'

    - name: Wait to avoid 'text file busy' issue
      pause:
        seconds: 2

    - name: Run update script
      command: /tmp/update.sh
      register: update_result
      ignore_errors: yes  # optional: to continue even if update fails

    - name: Show update result stdout
      debug:
        var: update_result.stdout_lines

    - name: Show update result stderr (if any)
      debug:
        var: update_result.stderr_lines

    - name: Copy notify.sh to target machine
      copy:
        src: notify.sh
        dest: /tmp/notify.sh
        mode: '0755'

    - name: Wait to avoid 'text file busy' issue before notify
      pause:
        seconds: 2

    - name: Run notify script
      command: /tmp/notify.sh
      register: notify_result
      ignore_errors: yes  # optional: same reason

    - name: Show notify result stdout
      debug:
        var: notify_result.stdout_lines

    - name: Show notify result stderr (if any)
      debug:
        var: notify_result.stderr_lines
