- name: Patch system and notify
  hosts: all
  become: yes
  vars:
    update_script_path: /tmp/update.sh
    notify_script_path: /tmp/notify.sh
    logo_path: /tmp/aravind.jpeg

  tasks:
    - name: 📤 Copy update script
      copy:
        src: files/update.sh
        dest: "{{ update_script_path }}"
        mode: '0755'

    - name: 📤 Copy notify script
      copy:
        src: files/notify.sh
        dest: "{{ notify_script_path }}"
        mode: '0755'

    - name: 🖼️ Copy image file
      copy:
        src: files/aravind.jpeg
        dest: "{{ logo_path }}"
        mode: '0644'

    - name: ▶️ Run update script asynchronously
      shell: "{{ update_script_path }}"
      async: 300
      poll: 0
      register: update_async
      changed_when: false

    - name: ✅ Print update result status
      async_status:
        jid: "{{ update_async.ansible_job_id }}"
      register: update_status
      until: update_status.finished
      retries: 60
      delay: 5

    - name: 📬 Notify completion
      shell: "{{ notify_script_path }}"
