- name: Patch system and notify
  hosts: all
  become: yes
  become_method: sudo
  tasks:

    - name: Copy update.sh to target machine
      copy:
        src: update.sh       # from Git repo
        dest: /tmp/update.sh # location on remote system
        mode: '0755'

    - name: Run update script
      shell: /tmp/update.sh
      register: update_result

    - name: Show update result stdout
      debug:
        var: update_result.stdout_lines

    - name: Show update result stderr (if any)
      debug:
        var: update_result.stderr_lines

    - name: Copy notify.sh to target machine
      copy:
        src: notify.sh
        dest: /tmp/notify.sh
        mode: '0755'

    - name: Run notify script
      shell: /tmp/notify.sh
      register: notify_result

    - name: Show notify result stdout
      debug:
        var: notify_result.stdout_lines

    - name: Show notify result stderr (if any)
      debug:
        var: notify_result.stderr_lines
