- name: Patch system and notify
  hosts: all
  become: yes
  vars:
    update_script_path: /tmp/update.sh
    notify_script_path: /tmp/notify.sh

  tasks:

    - name: 📤 Copy update script to remote host
      copy:
        src: update.sh
        dest: "{{ update_script_path }}"
        mode: '0755'
        force: yes
        diff: no     # ✅ Suppress showing file differences

    - name: ▶️ Run update script asynchronously
      shell: bash "{{ update_script_path }}"
      async: 600
      poll: 10
      register: update_result
      ignore_errors: yes

    - name: ✅ Print update result status
      debug:
        msg: "✅ Update script finished with RC={{ update_result.rc }}"

    - name: ❌ Fail if update script failed
      fail:
        msg: >-
          ❌ Update script failed.
          RC: {{ update_result.rc }}
          STDERR: {{ update_result.stderr | default('N/A') }}
      when: update_result.rc != 0

    - name: 📤 Copy notify script to remote host
      copy:
        src: notify.sh
        dest: "{{ notify_script_path }}"
        mode: '0755'
        force: yes
        diff: no     # ✅ Suppress showing file differences

    - name: ▶️ Run notify script
      shell: bash "{{ notify_script_path }}"
      register: notify_result
      ignore_errors: yes

    - name: 📬 Show notify script result
      debug:
        msg: "✅ Notify script finished with RC={{ notify_result.rc }}"

    - name: ❌ Fail if notify script failed
      fail:
        msg: >-
          ❌ Notify script failed.
          RC: {{ notify_result.rc }}
          STDERR: {{ notify_result.stderr | default('N/A') }}
      when: notify_result.rc != 0
