- name: 🚀 Patch and Notify
  hosts: all
  become: true

  tasks:
    - name: 📤 Copy update.sh
      copy:
        src: update.sh
        dest: /tmp/update.sh
        mode: '0755'
      diff: no

    - name: 📤 Copy notify.sh
      copy:
        src: notify.sh
        dest: /tmp/notify.sh
        mode: '0755'
      diff: no

    - name: ▶️ Run update script
      shell: bash /tmp/update.sh

    - name: 📧 Send patch notification
      shell: bash /tmp/notify.sh

    - name: 🧹 Cleanup scripts
      file:
        path: "/tmp/{{ item }}"
        state: absent
      loop:
        - update.sh
        - notify.sh
