- name: Patch system and notify
  hosts: all
  become: yes
  vars:
    update_script_path: /tmp/update.sh
    notify_script_path: /tmp/notify.sh
  tasks:

    - name: Copy update script to remote host
      copy:
        src: update.sh
        dest: "{{ update_script_path }}"
        mode: '0755'

    - name: Run update script
      shell: bash "{{ update_script_path }}"
      register: update_result
      ignore_errors: yes

    - name: Print update script result
      debug:
        var: update_result

    - name: Fail if update script failed
      fail:
        msg: "⚠️ Update script failed with error: {{ update_result.stderr }}"
      when: update_result.rc != 0

    - name: Copy notify script to remote host
      copy:
        src: notify.sh
        dest: "{{ notify_script_path }}"
        mode: '0755'

    - name: Run notify script
      shell: bash "{{ notify_script_path }}"
      register: notify_result
      ignore_errors: yes

    - name: Print notify script result
      debug:
        var: notify_result

    - name: Fail if notify script failed
      fail:
        msg: "⚠️ Notify script failed with error: {{ notify_result.stderr }}"
      when: notify_result.rc != 0
